### ISSUE TITLE
win10 python3.7.4跑不起来

### ISSUE THREAD

**Issue by CloverPHP** [ZephyrChole/PerfectedWechatPCAPI#2]
我下载下来跑不起来是怎么解？
```
Traceback (most recent call last):
  File "PerfectedWechatPCAPI.py", line 7, in <module>
    from WechatPCAPI import WechatPCAPI
ModuleNotFoundError: No module named 'WechatPCAPI'
```
win10 python3.7.4
```
python --version
Python 3.7.4
```

**Comment by ZephyrChole** [comment]
运行的文件需要在项目根目录下，请展示你的目录结构



---原始邮件---
发件人: "CloverPHP"<notifications@github.com&gt;
发送时间: 2020年11月20日(周五) 下午4:44
收件人: "ZephyrChole/PerfectedWechatPCAPI"<PerfectedWechatPCAPI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZephyrChole/PerfectedWechatPCAPI] win10 python3.7.4跑不起来 (#2)




 
我下载下来跑不起来是怎么解？
 Traceback (most recent call last):   File "PerfectedWechatPCAPI.py", line 7, in <module&gt;     from WechatPCAPI import WechatPCAPI ModuleNotFoundError: No module named 'WechatPCAPI'  
win10 python3.7.4
 python --version Python 3.7.4

**Comment by CloverPHP** [comment]
我刚才下载直接在根目录运行的，会不会因为环境问题找不到DLL? 目录如下
![screen](https://user-images.githubusercontent.com/3917451/99781396-c35e9380-2b52-11eb-99b3-85f63a70091f.png)

**Comment by ZephyrChole** [comment]
我会晚点回复你


---原始邮件---
发件人: &quot;CloverPHP&quot;<notifications@github.com&gt;
发送时间: 2020年11月20日(周五) 下午5:07
收件人: &quot;ZephyrChole/PerfectedWechatPCAPI&quot;<PerfectedWechatPCAPI@noreply.github.com&gt;;
抄送: &quot;Zephyr&quot;<1905616103@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [ZephyrChole/PerfectedWechatPCAPI] win10 python3.7.4跑不起来 (#2)




 
我刚才下载直接在根目录运行的，会不会因为环境问题找不到DLL? 目录如下
 
 
&mdash;

**Comment by CloverPHP** [comment]
好的，感谢大神。

**Comment by CloverPHP** [comment]
这是一个悲伤的故事，刚才闲来无事，把本南的python卸载重装之后它居然跑起来了

**Comment by ZephyrChole** [comment]
那就好😊



---原始邮件---
发件人: "CloverPHP"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 下午5:43
收件人: "ZephyrChole/PerfectedWechatPCAPI"<PerfectedWechatPCAPI@noreply.github.com&gt;;
抄送: "Zephyr"<1905616103@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [ZephyrChole/PerfectedWechatPCAPI] win10 python3.7.4跑不起来 (#2)




 
这是一个悲伤的故事，刚才闲来无事，把本南的python卸载重装之后它居然跑起来了

**Comment by CloverPHP** [comment]
环境问题

**Comment by grifterlv** [comment]
怎么解决的啊？ pycharm感觉import不了pyd文件啊。
我用了￼ spider， 下载了特定版本的微信 但是我登录微信以后 get_myself总是return false 是什么回事啊？

**Comment by grifterlv** [comment]
![image](https://user-images.githubusercontent.com/5957030/100479983-f3abb200-30bd-11eb-9e52-ba457fb8d5b4.jpeg)
我hao有这个error 并且run了这个code 永远也没办法登录成功 不知道为什么

**Comment by ZephyrChole** [comment]
那就好😊



---原始邮件---
发件人: "CloverPHP"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 下午5:43
收件人: "ZephyrChole/PerfectedWechatPCAPI"<PerfectedWechatPCAPI@noreply.github.com&gt;;
抄送: "Zephyr"<1905616103@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [ZephyrChole/PerfectedWechatPCAPI] win10 python3.7.4跑不起来 (#2)




 
这是一个悲伤的故事，刚才闲来无事，把本南的python卸载重装之后它居然跑起来了
